version: 2.1

orbs:
  npm: lifeway/npm-tools@0.0.6

executors:
  node:
    docker:
      - image: circleci/node:12

jobs:
  publish:
    steps:
      - run:
          name: npm/publish
          command: npm publish

workflows:
  checks-deploy:
    jobs:
      - npm/install:
          context: rundmg
          executor: node
      - npm/run-script:
          context: rundmg
          executor: node
          name: type-check
          script: type-check
          requires:
            - npm/install
      - npm/run-script:
          context: rundmg
          executor: node
          name: version-check
          script: version-check
          requires:
            - npm/install
      - npm/audit:
          context: rundmg
          requires:
            - npm/install
      - npm/test:
          context: rundmg
          executor: node
          requires:
            - npm/install
      - publish:
          executor: node
          context: rundmg
          requires:
            - npm/test
            - npm/audit
            - type-check
            - version-check
          filters:
            branches:
              only: master
