version: 2.1

orbs:
  npm: lifeway/npm-tools@0.0.6

executors:
  node:
    docker:
      - image: circleci/node:12

jobs:
  publish:
    executor: node
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: npm/publish
          command: npm publish

workflows:
  checks-deploy:
    jobs:
      - npm/install:
          context: &team-context rundmg
          executor: node
      - npm/run-script:
          context: *team-context
          executor: node
          name: type-check
          script: type-check
          requires:
            - npm/install
      - npm/run-script:
          context: *team-context
          executor: node
          name: version-check
          script: version-check
          requires:
            - npm/install
      - npm/run-script:
          context: *team-context
          executor: node
          name: audit
          script: audit
          requires:
            - npm/install
      - npm/test:
          context: *team-context
          executor: node
          requires:
            - npm/install
      - npm/run-script:
          context: *team-context
          executor: node
          name: lint
          script: lint
          requires:
            - npm/install
      - publish:
          context: *team-context
          requires:
            - npm/test
            - audit
            - lint
            - type-check
            - version-check
          filters:
            branches:
              only: master
